markdown: kramdown
highlighter: rouge
permalink: /:title.html
name: "Fishing Pool"

author: "FishingKing Czj"

excerpt_separator: "<!--more-->"



navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: RSS
    class: fa fa-rss
    href: /atom.xml

#social
github: "https://github.com/Zuofan"


siteurl: "https://fishingkingczj.github.io/"
