baseurl:
    url: https://fishingkingczj.github.io
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
name: "THE POOL"
kramdown:
    input: GFM

author: "FishingKing Czj"

excerpt_separator: "<!--more-->"



navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: RSS
    class: fa fa-rss
    href: /atom.xml

#social
github: https://github.com/FishingKingczj

siteurl: https://fishingkingczj.github.io
