siteurl: https://fishingkingczj.com
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
name: "THE POOL"
kramdown:
    input: GFM

excerpt_separator: "<!--more-->"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive
  - title: Tags
    class: fa fa-tags
    href: /tags
  - title: About
    class: fa fa-user
    href: /about
  - title: RSS
    class: fa fa-rss
    href: /atom

#social
github: https://github.com/FishingKingczj

author: FishingKing Czj